# Generated by Django 2.2.5 on 2019-09-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingfx', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Websites',
            new_name='Website',
        ),
    ]
